import { SurfSpot } from './../models/SurfSpot.model';
export class ListSpotService
{
  spotsList: SurfSpot[] = [
    {
      name: 'Le Verdon',
      description: 'Le Verdon est le spot de repli girondin où on peut surfer quand c’est onshore et/ou que ça sature sur la cote. On surf ici à marée haute uniquement pour que le swell rentre, les vagues sont creuses avec quelques tubes.',
      tide: 'Marée haute',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'O-NO',      
      windDirection: 'Ouest',
      waveSize: '1-6ft / 30cm-1m80',
      imagePathSpot: 'assets/imgs/spot/leverdon.jpg',
      imagePathTide: 'assets/imgs/tide/hightide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/W-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/west.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-6.png',
      adresse: 'Le Verdon-sur-Mer'
    },
    {
      name: 'Soulac',
      description: 'C’est toujours plus petit ici mais c’est le beachbreak qui est le plus tubulaire du Nord Médoc. On y trouve plus de gauches que de droites. Ça marche le mieux avec un vent de sud-est. On peut y surfer avec toutes les marées. Attention aux courants qui sont forts et aux quelques rochers.',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Sud-Est',
      waveSize: '1-6ft / 30cm-1m80',
      imagePathSpot: 'assets/imgs/spot/soulac.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/se.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-6.png',
      adresse: 'Soulac-sur-Mer'
    },
    {
      name: 'L\'Amélie',
      description: 'A côté de la digue et des blockhaus on trouve des vagues qui sont rapides et creuses. Le spot fonctionne avec toutes les marées et avec un vent d’est. Attention à ne pas taper les rochers et les débris des blockhaus. ',
      tide: 'Toutes marées',
      waveBreak: 'Jetée - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/lamelie.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/jetty.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'L\'Amélie, Soulac-sur-Mer'
    },
    {
      name: 'Montalivet',
      description: 'A Montalivet les vagues sont plus petites qu’à Lacanau, on peut facilement checker les vagues depuis le parking. C’est un beackbreak girondin classique avec des droites et des gauches qui fonctionnent par vent d’est et par toutes marées.',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/montalivet.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Montalivet'
    },
    {
      name: 'Hourtin',
      description: 'Beachbreak avec des vagues qui déroulent et qui peuvent également tuber. Le spot fonctionne de préférence sur une marée basse ou une mi-marée avec un vent d’est, la marée haute est à éviter. ',
      tide: 'Mi-marée et marée basse',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/hourtin.jpg',
      imagePathTide: 'assets/imgs/tide/midlowtide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Hourtin Plage, Hourtin'
    },
    {
      name: 'Carcans',
      description: 'Spot alternatif à Lacanau avec moins de monde l’été. Les vagues sont aussi consistantes et puissantes qu’à Lacanau. On y trouve de grands murs à manœuvres et quelques tubes. Ca marche par toutes marées avec de préférence un vent d’est.',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/carcans.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Carcans Plage, Carcans'
    },
    {
      name: 'Lacanau',
      description: 'Lacanau est le spot de surf girondin le plus connu. Lacanau est un lieu de compétition depuis 1979 : ASP Lacanau Pro, QS 3000 Lacanau Pro… C’est le spot qui tient le mieux la taille en gironde grâce aux immenses baïnes autour des digues. Depuis la centrale on peut checker les pics de la Nord, la Sud, Super Sud, etc. Beaucoup d’écoles et de loueurs de surf sont présents toute l’année. Le spot convient à tous les niveaux en fonction de la taille des vagues. Il y a beaucoup de monde et d’ambiance l’été.',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-10ft / 30cm-3m',
      imagePathSpot: 'assets/imgs/spot/lacanau.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-10.png',
      adresse: 'Lacanau Océan, Lacanau'
    },
    {
      name: 'Le Porge',
      description: 'Le Porge est le spot le plus proche de Bordeaux, ce qui ramène du monde les week-ends et l’été. Depuis le haut des grandes dunes on peut facilement checker les différents pics qu’offre le spot. A marée basse ca a tendance à fermer et ça déroule plus à mi-marée et marée haute.',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/leporge.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Le Porge-Océan, Le Porge'
    },
    {
      name: 'Le Grand-Crohot',
      description: 'Line-ups à la landaise, où les baïnes aident à la formation des vagues, les pics sont creux et consistants. Le spot est proche de Bordeaux et Andernos il y a souvent du monde les week-ends et l’été, mais on peut se décaler sur la plage nudiste du Petit Crohot. ',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/legrandcrohot.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Le grand crohot, Lège-Cap-Ferret'
    },
    {
      name: 'Le Truc Vert',
      description: 'Le spot le plus connus du Cap Ferret grâce au grand camping juste à côté et avec de bons bancs de sables. Attention l’été le spot est difficile d’accès à cause de la circulation qui sature.',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-10ft / 30cm-3m',
      imagePathSpot: 'assets/imgs/spot/letrucvert.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-10.png',
      adresse: 'Plage Du Truc Vert, Lège-Cap-Ferret'
    },
    {
      name: 'L\'Horizon',
      description: 'Spot plus tranquille que Le Truc Vert, il y a moins de monde l’été mais l’accès au spot est aussi difficile à cause de la circulation. On s’approche de la pointe du Cap-Ferret les courants y sont forts et les bancs de sables bougent régulièrement. ',
      tide: 'Toutes marées',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/lhorizon.jpg',
      imagePathTide: 'assets/imgs/tide/alltide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Plage de l\'Horizon, Lège-Cap-Ferret'
    },
    {
      name: 'La Pointe',
      description: 'Spot de repli à l’entrée du bassin d’Arcachon ce qui génère beaucoup de courant. Le spot fonctionne quand c’est onshore et/ou que ça sature sur la cote. On y trouve beaucoup de droites creuses. Le spot fonctionne de préférence sur une marée haute ou une mi-marée.',
      tide: 'Marée haute et mi-marée',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Ouest',
      waveSize: '1-4ft / 30cm-1m20',
      imagePathSpot: 'assets/imgs/spot/lapointe.jpg',
      imagePathTide: 'assets/imgs/tide/highmidtide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/west.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-4.png',
      adresse: 'Pointe du Cap Ferret, Allée de la Pointe, Lège-Cap-Ferret'
    },
    {
      name: 'La Salie',
      description: 'La Salie est le dernier spot de surf girondin avant les Landes. Le spot tient bien la taille et on trouve souvent des vagues tubulaires proches du bord. Il y a deux accès pour le spot, la Salie Nord et la Salie Sud. Le spot est proche d’Arcachon ce qui ramène du monde toute l’année. Au sud on trouve le Wharf qui malheureusement crache des eaux à l’odeur pas très rassurante et la baignade y est théoriquement interdite. ',
      tide: 'Mi-marée et marée basse',
      waveBreak: 'Beachbreak - Droites et gauches',
      seaBottom: 'Sable',        
      swellDirection: 'SO-NO',      
      windDirection: 'Est',
      waveSize: '1-8ft / 30cm-2m40',
      imagePathSpot: 'assets/imgs/spot/lasalie.jpg',
      imagePathTide: 'assets/imgs/tide/midlowtide.png',
      imagePathWaveBreak: 'assets/imgs/waveBreak/rightandleft.png',
      imagePathSeaBottom: 'assets/imgs/seaBottom/sand.png',
      imagePathSwellDirection: 'assets/imgs/swellDirection/SW-NW.png',
      imagePathWindDirection: 'assets/imgs/windDirection/east.png',
      imagePathWaveSize: 'assets/imgs/waveSize/1-8.png',
      adresse: 'Plage de la Salie-Nord, La Teste-de-Buch'
    }
  ];
}